### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#20]
Updating to be - age of the project (days) / recency of the last pull request (days) 

50/50 split of the below factors. 
Frequency - number of pull requests over the age of the project
Recent -  not really sure how to gauge this part

**Comment by Matthew-Nale** [comment]
In the pull_requests.py file, a function has been made to determine the time elapsed since the last Pull Request. Finding an equation to determine weight based on time elapsed should be explored. Currently, there is also another function to obtain the dates of all pull requests, which could factor into the frequency determination

**Comment by Matthew-Nale** [comment]
Since the obtaining of the pull_request.py is mostly finished, this issue can be closed. If needed, add additional functions to the file

**Comment by Matthew-Nale** [comment]
Pull request has the errors updated, and has been completed
